// ===== 套餐 =====
export const PACKAGES = [
  {
    id: 'power',
    title: '動力覺醒套餐',
    image: '/src/assets/images/package-power.png',
    items: [
      { no: 1, name: 'V3s+ 變速箱晶片', price: 18000 },
      { no: 2, name: 'EP 優化精靈',      price: 3980 },
      { no: 3, name: '動力考爾電腦',     price: 12000 },
    ],
    combos: [
      { label: 'A', desc: '1+2',   price: 20000, save: 1980 },
      { label: 'B', desc: '1+3',   price: 28000, save: 2000 },
      { label: 'C', desc: '1+2+3', price: 30000, save: 3980 },
      { label: 'D', desc: '2+3',   price: 15000, save: 980 },
    ],
    notes: [
      { name: 'V3s+ 運動版變速箱晶片', desc: '除了基礎變速箱V1邏輯優化，又更深層的去強化原廠所不足地方' },
      { name: 'EP 優化精靈',           desc: '一個穩壓讓全車電場穩定與給好電的產品，進而增加扭力' },
      { name: '動力考爾電腦',           desc: '建立在考爾加強點火之上由考爾進去去解放原廠封印的動力，更可以提升駕駛的娛樂性，車主可自由恢復原廠，不破保' },
    ],
  },
  {
    id: 'micro',
    title: '微動力升級方案',
    subtitle: '老客戶專屬 V1升級V3',
    image: '/src/assets/images/package-micro.png',
    items: [
      { no: 1, name: 'V3s+ 變速箱晶片', price: 18000 },
      { no: 2, name: '四點接地線',       price: 5000 },
      { no: 3, name: '動力考爾電腦',     price: 12000 },
    ],
    combos: [
      { label: 'A', desc: '1+2',   price: 15000, save: 8000 },
      { label: 'B', desc: '1+2+3', price: 25000, save: 10000 },
      { label: 'C', desc: '2+3',   price: 13000, save: 4000 },
    ],
    notes: [
      { name: 'V3s+ 運動版變速箱晶片', desc: '除了基礎變速箱V1邏輯優化，又更深層的去強化原廠所不足地方' },
      { name: '四點接地線',             desc: '市面上大多只有兩點接地，不過每家做法都有道理\n四點接地更直覺的讓負極回流更加順暢，減少回流塞車情形' },
      { name: '動力考爾電腦',           desc: '建立在考爾加強點火之上由考爾進去去解放原廠封印的動力，更可以提升駕駛的娛樂性，車主可自由恢復原廠，不破保' },
    ],
  },
  {
    id: 'chassis',
    title: '控骨力套餐',
    image: '/src/assets/images/package-chassis.png',
    items: [
      { no: 1, name: '升級版避震器',     price: 32000 },
      { no: 2, name: '工字梁襯套',       price: 2000 },
      { no: 3, name: '藍藍的後防傾',     price: 16500 },
      { no: 4, name: '室內駕駛拉桿',     price: 4980 },
      { no: 5, name: '室內後箱上拉桿',   price: 5980 },
    ],
    combos: [
      { label: 'A', desc: '1+2',     price: 32000, save: 2000 },
      { label: 'B', desc: '1+2+3',   price: 46000, save: 4500 },
      { label: 'C', desc: '4+5',     price: 9999,  save: 961 },
      { label: 'D', desc: '我全都要', price: 54000, save: 7460 },
    ],
    notes: [],
  },
];

// ===== 完整服務項目 =====
export const SERVICE_CATEGORIES = [
  {
    id: 'bumper',
    title: '防撞桿／重力盤',
    icon: '🛡️',
    items: [
      { name: '大維（前後）',           price: '28,000' },
      { name: '金剛（前後）',           price: '26,500' },
      { name: 'JST（前後）',            price: '22,600' },
      { name: '金剛－八尺重力盤',       price: '39,500' },
      { name: '金剛－塑木導流板',       price: '2,500' },
      { name: '金剛－橫桿',             price: '21,500' },
      { name: '多功能承重防撞桿',       price: '18,500' },
      { name: '橫桿',                   price: '18,000 up' },
      { name: '鐵皮硬派前防撞桿',       price: '13,500' },
      { name: '鐵皮硬派前防撞桿＋翅膀', price: '詢價' },
    ],
  },
  {
    id: 'chassis',
    title: '底盤系列',
    icon: '⚙️',
    items: [
      { name: 'J&J 避震器',               price: '28,000' },
      { name: '黃金升級版 J&J 避震器',    price: '32,000' },
      { name: 'D2 避震器',                price: '30,000' },
      { name: 'KS 升級版避震器',          price: '35,000', note: '老婆大人' },
      { name: '三角台',                   price: '6,500' },
      { name: '前防傾桿含李仔串',         price: '14,000' },
      { name: '後防傾桿含李仔串',         price: '16,500' },
      { name: '變速箱上移套件',           price: '6,500' },
      { name: '襯套',                     price: '2,000' },
      { name: '鋁合金變速箱下護板',       price: '4,500' },
      { name: '鋼板優力膠',               price: '6,500', note: '鐵皮避震車主優惠價 5,000' },
    ],
  },
  {
    id: 'power',
    title: '動力系列',
    icon: '⚡',
    items: [
      { name: '優化精靈',     price: '3,980' },
      { name: '變速箱晶片',   price: '13,500' },
      { name: '油門加速器',   price: '5,600' },
      { name: '烤爾電腦',     price: '12,000' },
      { name: '強化考爾',     price: '12,500' },
    ],
  },
  {
    id: 'intake',
    title: '進氣系列',
    icon: '🌬️',
    items: [
      { name: '進氣肥腸',     price: '2,850' },
      { name: '加大蝴蝶閥',   price: '14,500' },
      { name: '高流量濾網',   price: '1,500' },
      { name: '曲軸負壓',     price: '4,500' },
    ],
  },
  {
    id: 'brake',
    title: '制動系列',
    icon: '🔴',
    items: [
      { name: '來令',                price: '2,700' },
      { name: '金屬油管',            price: '5,000' },
      { name: 'UBS 專用卡鉗',        price: '27,500' },
      { name: 'UBS 股改碟',          price: '45,000' },
      { name: '一體鍛造鏤空卡鉗',    price: '43,500' },
      { name: '304 浮動碟（黑紫黃紅橘）', price: '詢價' },
    ],
  },
  {
    id: 'electric',
    title: '電系相關',
    icon: '📡',
    items: [
      { name: '環景一體機（4+64）',      price: '22,000', note: '12.8寸 8核心' },
      { name: '環景一體機（8+128）',     price: '25,000', note: '12.8寸 8核心' },
      { name: '前門 5寸分音喇叭',        price: '7,000' },
      { name: '前門 6.5寸分音喇叭',      price: '8,500' },
      { name: '後面 2.5寸中高音喇叭',    price: '4,500' },
      { name: '先鋒薄型重低音',          price: '9,000' },
      { name: '70邁流媒體',              price: '8,000' },
      { name: 'DOD RXW969',             price: '11,000' },
      { name: '行車喇叭',               price: '1,300' },
      { name: '霧燈罩－標準',           price: '1,000' },
      { name: '霧燈罩－客製',           price: '1,500～1,800' },
      { name: 'USB 充電孔',             price: '800' },
    ],
  },
  {
    id: 'insulation',
    title: '隔熱／隔音系列',
    icon: '🔇',
    items: [
      { name: '隔熱紙',                      price: '12,000 up' },
      { name: '後段底盤防鏽漆',              price: '2,500' },
      { name: '專用 PET 防火隔熱板（全車）', price: '6,000' },
      { name: '隔音制震全車',               price: '44,000', note: '完工價格以施作部分為準' },
    ],
  },
  {
    id: 'camping',
    title: '露營系列',
    icon: '⛺',
    items: [
      { name: '車頂探照燈',                price: '詢價' },
      { name: '防撞桿探照燈',              price: '詢價' },
      { name: 'SRNE 駐車電池（314Ah）',    price: '39,900', note: '保固三年保修兩年' },
      { name: '椅下電池（470Ah）',         price: '51,800', note: '保固兩年' },
      { name: '太陽能軟板',               price: '59,860' },
      { name: '太陽能硬板',               price: '21,000' },
      { name: '外掛冷器',                 price: '35,000' },
      { name: '並聯冷器',                 price: '45,800' },
      { name: '19吋吸頂電視',             price: '詢價' },
      { name: '電動內開門',               price: '詢價' },
    ],
  },
  {
    id: 'bed',
    title: '百變床椅系列',
    icon: '🛏️',
    items: [
      { name: '原廠椅平整墊三片',         price: '500' },
      { name: '鐵皮抱枕被',              price: '500' },
      { name: '三座一體舒適床椅',         price: '25,000', note: '可雙色不另計費' },
      { name: '三座一體包袱床椅',         price: '28,000', note: '均可客製化床椅總高度，腳座台灣手工製造' },
      { name: '床椅加高',                price: '+3,000' },
      { name: '改 6/4 分體',             price: '+3,000' },
      { name: '升級納帕皮革',             price: '+3,000' },
      { name: '升級頂級油蠟皮',           price: '+6,000' },
      { name: '其他客製化需求',           price: '詢價回覆' },
    ],
  },
  {
    id: 'exterior',
    title: '外觀系列',
    icon: '✨',
    items: [
      { name: '前貫穿燈',             price: '5,980' },
      { name: '後貫穿燈',             price: '5,980' },
      { name: '氣霸燈',              price: '1,500' },
      { name: '鐵皮同款排氣管',       price: '25,000', note: '老婆大人款，遙控閥門' },
      { name: '防石網',              price: '1,300' },
      { name: '狗骨頭',              price: '4,980' },
      { name: '尊豪（小）椅座頭枕',   price: '1,700' },
      { name: '尊爵（大）椅座頭枕',   price: '1,900' },
      { name: '脫困板',              price: '1,400' },
      { name: '三刀流白金霧燈',       price: '3,000' },
      { name: '黃金霧燈',            price: '1,400' },
      { name: '魚眼霧燈',            price: '7,500' },
      { name: '魚眼大燈',            price: '18,000' },
      { name: '黑化滑軌',            price: '6,000' },
      { name: '尾門內外護板',         price: '1,800' },
      { name: '內拉桿',              price: '5,980' },
      { name: '戰術板',              price: '3,980' },
      { name: '輪框輪胎',            price: '22,800 up' },
      { name: '尾箱燈',              price: '2,500' },
      { name: '光明燈',              price: '1,800' },
      { name: '【雨盾】雨刷',         price: '800' },
      { name: '【雨盾】雨刷（黑色）', price: '600' },
      { name: '一紗一布窗',           price: '3,000' },
      { name: '擋泥板',              price: '700' },
      { name: '登車把手',            price: '2,500' },
      { name: '開關門把手（單）',     price: '1,699' },
      { name: '開關門把手（雙）',     price: '3,000' },
      { name: '方向盤球－球球',       price: '450 up' },
      { name: '方向盤球－菩提子',     price: '650' },
      { name: '碳匠尾翼',            price: '5,500' },
      { name: 'GP 尾翼',             price: '3,980' },
      { name: '胖魚頭',              price: '1,800' },
      { name: '側飾板',              price: '4,000 up' },
      { name: '輪拱飾板',            price: '3,000 up' },
      { name: '門碗',                price: '800' },
      { name: '恐龍漆單色',           price: '50,000' },
      { name: '恐龍漆雙色',           price: '55,000' },
      { name: '客製化方向盤',         price: '14,000', note: '碳纖維金箔' },
      { name: '中央扶手',            price: '4,500' },
      { name: 'M8 腳踏墊',           price: '3,500' },
      { name: '全車防水墊',           price: '4,500' },
      { name: '防水後地墊',           price: '3,000' },
      { name: '全包覆地墊',           price: '25,000' },
      { name: '尾箱內護甲',           price: '3,500' },
    ],
  },
];
